INSERT INTO TB_CLIENT (CPF, NAME_CLIENT)  VALUES('12345', 'Carxl');
INSERT INTO TB_ORDER (NUMBER,STATUS,TOTAL_VALUE,CLIENT_ID ) VALUES(104, 'CRIADO', 230, 1);
INSERT INTO TB_ITEM (NAME_ITEM , PRICE , QUANTITY )  VALUES('celular', 1323, 2);
INSERT INTO TB_ORDER_ITEMS (ORDER_ID  , ITEMS_ID  )  VALUES(1, 1);